SET FOREIGN_KEY_CHECKS = 0;

CREATE TABLE `balance_required_area_exclusions` (
  `admission_year_short` int NOT NULL,
  `admission_year` int NOT NULL,
  `is_deleted` bit(1) NOT NULL,
  `created_at` datetime(6) DEFAULT NULL,
  `deleted_at` datetime(6) DEFAULT NULL,
  `id` bigint NOT NULL AUTO_INCREMENT,
  `semester_at` varchar(255) DEFAULT NULL,
  `balance_required_area` enum('CONVERGENCE_AND_CREATIVITY','CULTURE_ARTS','ECONOMY_SOCIETY','HISTORY_THOUGHT','NATURE_SCIENCE') NOT NULL,
  `dept_group` enum('ACADEMIC_DIVISION_2','AI_CONVERGENCE_COLLEGE','ARTS_AND_PHYSICAL_EDUCATION_COLLEGE','BUSINESS_ADMINISTRATION_COLLEGE','BUSINESS_AND_ECONOMICS_COLLEGE','DAEYANG_HUMANITY_COLLEGE','ELECTRONICS_AND_INFORMATION_ENGINEERING_COLLEGE','ENGINEERING_COLLEGE','HOSPITALITY_AND_TOURISM_COLLEGE','INTERDISCIPLINARY_CONVERGENCE_MAJOR','LAW','LIBERAL_ARTS_COLLEGE','LIFE_SCIENCES_COLLEGE','NATURAL_SCIENCES_COLLEGE','SEJONG_INTERNATIONAL_COLLEGE','SOCIAL_SCIENCES_COLLEGE','SOFTWARE_CONVERGENCE_COLLEGE') NOT NULL,
  `updated_at` datetime(6) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
CREATE TABLE `balance_required_course_area_map` (
  `admission_year` int NOT NULL,
  `admission_year_short` int NOT NULL,
  `is_deleted` bit(1) NOT NULL,
  `created_at` datetime(6) DEFAULT NULL,
  `deleted_at` datetime(6) DEFAULT NULL,
  `id` bigint NOT NULL AUTO_INCREMENT,
  `curi_nm` varchar(255) NOT NULL,
  `curi_no` varchar(255) NOT NULL,
  `semester_at` varchar(255) DEFAULT NULL,
  `balance_required_area` enum('CONVERGENCE_AND_CREATIVITY','CULTURE_ARTS','ECONOMY_SOCIETY','HISTORY_THOUGHT','NATURE_SCIENCE') NOT NULL,
  `updated_at` datetime(6) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
CREATE TABLE `balance_required_rules` (
  `admission_year` int NOT NULL,
  `admission_year_short` int NOT NULL,
  `is_deleted` bit(1) NOT NULL,
  `required` bit(1) NOT NULL,
  `required_areas_cnt` int NOT NULL,
  `required_credits` int NOT NULL,
  `created_at` datetime(6) DEFAULT NULL,
  `deleted_at` datetime(6) DEFAULT NULL,
  `id` bigint NOT NULL AUTO_INCREMENT,
  `dept_cd` varchar(255) NOT NULL,
  `dept_nm` varchar(255) NOT NULL,
  `note` varchar(255) DEFAULT NULL,
  `semester_at` varchar(255) DEFAULT NULL,
  `updated_at` datetime(6) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
CREATE TABLE `baskets` (
  `out_limit_rcnt` int DEFAULT NULL,
  `rcnt` int DEFAULT NULL,
  `remain_other_rcnt` int DEFAULT NULL,
  `remain_out_rcnt` int DEFAULT NULL,
  `tot_limit_rcnt` int DEFAULT NULL,
  `tot_out_rcnt` int DEFAULT NULL,
  `tot_rcnt` int DEFAULT NULL,
  `created_at` timestamp(6) NULL DEFAULT NULL,
  `id` bigint NOT NULL AUTO_INCREMENT,
  `subject_id` bigint DEFAULT NULL,
  `class` varchar(255) DEFAULT NULL,
  `curi_no` varchar(255) DEFAULT NULL,
  `dept_cd` varchar(255) DEFAULT NULL,
  `orgn_clsf_cd` varchar(255) DEFAULT NULL,
  `semester_at` varchar(255) DEFAULT NULL,
  `smt_cd` varchar(255) DEFAULT NULL,
  `student_dept_cd` varchar(255) DEFAULT NULL,
  `student_dept_cd_nm` varchar(255) DEFAULT NULL,
  `student_div` varchar(255) DEFAULT NULL,
  `student_div_nm` varchar(255) DEFAULT NULL,
  `year` varchar(255) DEFAULT NULL,
  `is_deleted` tinyint(1) NOT NULL DEFAULT '0',
  `deleted_at` timestamp NULL DEFAULT NULL,
  `updated_at` datetime(6) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `subjects_id_idx` (`subject_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
CREATE TABLE `classic_cert_criteria` (
  `admission_year` int NOT NULL,
  `admission_year_short` int NOT NULL,
  `is_deleted` bit(1) NOT NULL,
  `required_count_eastern` int NOT NULL,
  `required_count_eastern_and_western` int NOT NULL,
  `required_count_science` int NOT NULL,
  `required_count_western` int NOT NULL,
  `total_required_count` int NOT NULL,
  `created_at` datetime(6) DEFAULT NULL,
  `deleted_at` datetime(6) DEFAULT NULL,
  `id` bigint NOT NULL AUTO_INCREMENT,
  `note` varchar(255) DEFAULT NULL,
  `semester_at` varchar(255) DEFAULT NULL,
  `updated_at` datetime(6) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
CREATE TABLE `coding_cert_criteria` (
  `admission_year_short` int NOT NULL,
  `admission_year` int NOT NULL,
  `is_deleted` bit(1) NOT NULL,
  `tosc_min_level` int NOT NULL,
  `created_at` datetime(6) DEFAULT NULL,
  `deleted_at` datetime(6) DEFAULT NULL,
  `id` bigint NOT NULL AUTO_INCREMENT,
  `alt1_curi_nm` varchar(255) DEFAULT NULL,
  `alt1_curi_no` varchar(255) DEFAULT NULL,
  `alt1_min_grade` varchar(255) DEFAULT NULL,
  `alt2_curi_nm` varchar(255) DEFAULT NULL,
  `alt2_curi_no` varchar(255) DEFAULT NULL,
  `alt2_min_grade` varchar(255) DEFAULT NULL,
  `note` varchar(255) DEFAULT NULL,
  `semester_at` varchar(255) DEFAULT NULL,
  `coding_target_type` enum('CODING_MAJOR','EXEMPT','NON_MAJOR') NOT NULL,
  `updated_at` datetime(6) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
CREATE TABLE `completed_courses` (
  `created_at` datetime(6) DEFAULT NULL,
  `id` bigint NOT NULL AUTO_INCREMENT,
  `deleted_at` datetime(6) DEFAULT NULL,
  `is_deleted` bit(1) NOT NULL,
  `semester_at` varchar(255) DEFAULT NULL,
  `category_type` enum('COMMON_REQUIRED','BALANCE_REQUIRED','ACADEMIC_BASIC','GENERAL_ELECTIVE','GENERAL','MAJOR_REQUIRED','MAJOR_ELECTIVE','MAJOR_BASIC','TOTAL_COMPLETION') DEFAULT NULL,
  `credits` double DEFAULT NULL,
  `curi_nm` varchar(255) DEFAULT NULL,
  `curi_no` varchar(255) DEFAULT NULL,
  `grade` varchar(255) DEFAULT NULL,
  `major_scope` enum('PRIMARY','SECONDARY') DEFAULT NULL,
  `selected_area` varchar(255) DEFAULT NULL,
  `user_id` bigint NOT NULL,
  `is_earned` bit(1) DEFAULT NULL,
  `updated_at` datetime(6) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
CREATE TABLE `course_replacements` (
  `admission_year_short` int NOT NULL,
  `admission_year` int NOT NULL,
  `enabled` bit(1) NOT NULL,
  `is_deleted` bit(1) NOT NULL,
  `created_at` datetime(6) DEFAULT NULL,
  `deleted_at` datetime(6) DEFAULT NULL,
  `id` bigint NOT NULL AUTO_INCREMENT,
  `current_curi_nm` varchar(255) NOT NULL,
  `current_curi_no` varchar(255) NOT NULL,
  `legacy_curi_nm` varchar(255) NOT NULL,
  `note` varchar(255) DEFAULT NULL,
  `semester_at` varchar(255) DEFAULT NULL,
  `updated_at` datetime(6) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
CREATE TABLE `credit_criteria` (
  `admission_year_short` int NOT NULL,
  `admission_year` int NOT NULL,
  `enabled` bit(1) NOT NULL,
  `is_deleted` bit(1) NOT NULL,
  `required_credits` int NOT NULL,
  `created_at` datetime(6) DEFAULT NULL,
  `deleted_at` datetime(6) DEFAULT NULL,
  `id` bigint NOT NULL AUTO_INCREMENT,
  `dept_cd` varchar(255) NOT NULL,
  `dept_nm` varchar(255) NOT NULL,
  `note` varchar(255) DEFAULT NULL,
  `semester_at` varchar(255) DEFAULT NULL,
  `category_type` enum('ACADEMIC_BASIC','BALANCE_REQUIRED','COMMON_REQUIRED','GENERAL_ELECTIVE','MAJOR_BASIC','MAJOR_ELECTIVE','MAJOR_REQUIRED','TOTAL_COMPLETION') NOT NULL,
  `major_scope` enum('PRIMARY','SECONDARY') NOT NULL,
  `major_type` enum('ALL','DOUBLE','SINGLE') NOT NULL,
  `updated_at` datetime(6) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
CREATE TABLE `custom_schedule` (
  `id` bigint NOT NULL,
  `timetable_id` bigint DEFAULT NULL,
  `subject_name` varchar(255) NOT NULL,
  `professor_name` varchar(255) DEFAULT NULL,
  `location` varchar(255) DEFAULT NULL,
  `time_slots` json DEFAULT NULL,
  `semester_at` varchar(255) DEFAULT NULL,
  `created_at` datetime(6) DEFAULT NULL,
  `deleted_at` datetime(6) DEFAULT NULL,
  `is_deleted` tinyint(1) DEFAULT NULL,
  `updated_at` datetime(6) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `fk_custom_schedule_timetable` (`timetable_id`),
  CONSTRAINT `fk_custom_schedule_timetable` FOREIGN KEY (`timetable_id`) REFERENCES `time_table` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
CREATE TABLE `departments` (
  `created_at` timestamp(6) NULL DEFAULT NULL,
  `id` bigint NOT NULL AUTO_INCREMENT,
  `dept_cd` varchar(255) DEFAULT NULL,
  `dept_degree` varchar(255) DEFAULT NULL,
  `semester_at` varchar(255) DEFAULT NULL,
  `is_deleted` tinyint(1) NOT NULL DEFAULT '0',
  `deleted_at` timestamp NULL DEFAULT NULL,
  `updated_at` datetime(6) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
CREATE TABLE `double_credit_criteria` (
  `admission_year` int NOT NULL,
  `admission_year_short` int NOT NULL,
  `enabled` bit(1) NOT NULL,
  `is_deleted` bit(1) NOT NULL,
  `required_credits` int NOT NULL,
  `created_at` datetime(6) DEFAULT NULL,
  `deleted_at` datetime(6) DEFAULT NULL,
  `id` bigint NOT NULL AUTO_INCREMENT,
  `note` varchar(255) DEFAULT NULL,
  `primary_dept_cd` varchar(255) NOT NULL,
  `primary_dept_nm` varchar(255) NOT NULL,
  `secondary_dept_cd` varchar(255) NOT NULL,
  `secondary_dept_nm` varchar(255) NOT NULL,
  `semester_at` varchar(255) DEFAULT NULL,
  `category_type` enum('ACADEMIC_BASIC','BALANCE_REQUIRED','COMMON_REQUIRED','GENERAL_ELECTIVE','MAJOR_BASIC','MAJOR_ELECTIVE','MAJOR_REQUIRED','TOTAL_COMPLETION') NOT NULL,
  `major_scope` enum('PRIMARY','SECONDARY') NOT NULL,
  `major_type` enum('ALL','DOUBLE','SINGLE') NOT NULL,
  `updated_at` datetime(6) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
CREATE TABLE `english_cert_criteria` (
  `admission_year_short` int NOT NULL,
  `admission_year` int NOT NULL,
  `alt_curi_credit` int DEFAULT NULL,
  `gtelp_level` int NOT NULL,
  `gtelp_min_score` int NOT NULL,
  `gtelp_speaking_level` int NOT NULL,
  `is_deleted` bit(1) NOT NULL,
  `new_teps_min_score` int NOT NULL,
  `teps_min_score` int NOT NULL,
  `toefl_ibt_min_score` int NOT NULL,
  `toeic_min_score` int NOT NULL,
  `created_at` datetime(6) DEFAULT NULL,
  `deleted_at` datetime(6) DEFAULT NULL,
  `id` bigint NOT NULL AUTO_INCREMENT,
  `alt_curi_nm` varchar(255) DEFAULT NULL,
  `alt_curi_no` varchar(255) DEFAULT NULL,
  `note` varchar(255) DEFAULT NULL,
  `opic_min_level` varchar(255) NOT NULL,
  `semester_at` varchar(255) DEFAULT NULL,
  `toeic_speaking_min_level` varchar(255) NOT NULL,
  `english_target_type` enum('ENGLISH_MAJOR','EXEMPT','NON_MAJOR') NOT NULL,
  `updated_at` datetime(6) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
CREATE TABLE `everytime` (
  `id` int DEFAULT NULL,
  `code` varchar(512) DEFAULT NULL,
  `name` varchar(512) DEFAULT NULL,
  `professor` varchar(512) DEFAULT NULL,
  `type` varchar(512) DEFAULT NULL,
  `grade` int DEFAULT NULL,
  `time` varchar(512) DEFAULT NULL,
  `place` varchar(512) DEFAULT NULL,
  `credit` int DEFAULT NULL,
  `popular` int DEFAULT NULL,
  `target` varchar(512) DEFAULT NULL,
  `notice` varchar(512) DEFAULT NULL,
  `lectureId` int DEFAULT NULL,
  `lectureRate` varchar(512) DEFAULT NULL,
  `subjectCode` int DEFAULT NULL,
  `classCode` int DEFAULT NULL,
  `is_deleted` tinyint(1) NOT NULL DEFAULT '0',
  `deleted_at` timestamp NULL DEFAULT NULL,
  `semester_at` varchar(255) DEFAULT NULL,
  `created_at` timestamp(6) NULL DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
CREATE TABLE `graduation_cert_rules` (
  `admission_year_short` int NOT NULL,
  `admission_year` int NOT NULL,
  `is_deleted` bit(1) NOT NULL,
  `created_at` datetime(6) DEFAULT NULL,
  `deleted_at` datetime(6) DEFAULT NULL,
  `id` bigint NOT NULL AUTO_INCREMENT,
  `semester_at` varchar(255) DEFAULT NULL,
  `graduation_cert_rule_type` enum('BOTH_REQUIRED','TWO_OF_THREE') NOT NULL,
  `updated_at` datetime(6) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
CREATE TABLE `graduation_check` (
  `can_graduate` bit(1) NOT NULL,
  `is_deleted` bit(1) NOT NULL,
  `remaining_credits` double NOT NULL,
  `required_total_credits` int NOT NULL,
  `total_credits` double NOT NULL,
  `created_at` datetime(6) DEFAULT NULL,
  `deleted_at` datetime(6) DEFAULT NULL,
  `user_id` bigint NOT NULL,
  `semester_at` varchar(255) DEFAULT NULL,
  `updated_at` datetime(6) DEFAULT NULL,
  PRIMARY KEY (`user_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
CREATE TABLE `graduation_check_balance_area_result` (
  `is_deleted` bit(1) NOT NULL,
  `created_at` datetime(6) DEFAULT NULL,
  `deleted_at` datetime(6) DEFAULT NULL,
  `id` bigint NOT NULL AUTO_INCREMENT,
  `user_id` bigint NOT NULL,
  `semester_at` varchar(255) DEFAULT NULL,
  `area` enum('CONVERGENCE_AND_CREATIVITY','CULTURE_ARTS','ECONOMY_SOCIETY','HISTORY_THOUGHT','NATURE_SCIENCE') NOT NULL,
  `updated_at` datetime(6) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
CREATE TABLE `graduation_check_category_result` (
  `is_satisfied` bit(1) NOT NULL,
  `is_deleted` bit(1) NOT NULL,
  `my_credits` double NOT NULL,
  `remaining_credits` double NOT NULL,
  `required_credits` int NOT NULL,
  `created_at` datetime(6) DEFAULT NULL,
  `deleted_at` datetime(6) DEFAULT NULL,
  `id` bigint NOT NULL AUTO_INCREMENT,
  `user_id` bigint NOT NULL,
  `semester_at` varchar(255) DEFAULT NULL,
  `category_type` enum('ACADEMIC_BASIC','BALANCE_REQUIRED','COMMON_REQUIRED','GENERAL_ELECTIVE','MAJOR_BASIC','MAJOR_ELECTIVE','MAJOR_REQUIRED','TOTAL_COMPLETION') NOT NULL,
  `major_scope` enum('PRIMARY','SECONDARY') NOT NULL,
  `updated_at` datetime(6) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `UKl4mqrm6p4fhrhsgi2hqe1h458` (`user_id`,`major_scope`,`category_type`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
CREATE TABLE `graduation_check_cert_result` (
  `classics_total_my_count` int NOT NULL,
  `classics_total_required_count` int NOT NULL,
  `is_classics_cert_passed` bit(1) NOT NULL,
  `is_classics_eastern_and_western_cert_passed` bit(1) NOT NULL,
  `is_classics_eastern_cert_passed` bit(1) NOT NULL,
  `is_classics_science_cert_passed` bit(1) NOT NULL,
  `is_classics_western_cert_passed` bit(1) NOT NULL,
  `is_coding_cert_passed` bit(1) NOT NULL,
  `is_english_cert_passed` bit(1) NOT NULL,
  `is_satisfied` bit(1) NOT NULL,
  `my_count_eastern` int NOT NULL,
  `my_count_eastern_and_western` int NOT NULL,
  `my_count_science` int NOT NULL,
  `my_count_western` int NOT NULL,
  `passed_count` int NOT NULL,
  `required_count_eastern` int NOT NULL,
  `required_count_eastern_and_western` int NOT NULL,
  `required_count_science` int NOT NULL,
  `required_count_western` int NOT NULL,
  `required_pass_count` int NOT NULL,
  `user_id` bigint NOT NULL,
  `graduation_cert_rule_type` enum('BOTH_REQUIRED','TWO_OF_THREE') NOT NULL,
  PRIMARY KEY (`user_id`),
  CONSTRAINT `FK27rj7h2aucmvft6nejddwl7hm` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
CREATE TABLE `graduation_department_info` (
  `admission_year` int NOT NULL,
  `admission_year_short` int NOT NULL,
  `is_deleted` bit(1) NOT NULL,
  `created_at` datetime(6) DEFAULT NULL,
  `deleted_at` datetime(6) DEFAULT NULL,
  `id` bigint NOT NULL AUTO_INCREMENT,
  `college_nm` varchar(255) NOT NULL,
  `dept_cd` varchar(255) DEFAULT NULL,
  `dept_nm` varchar(255) NOT NULL,
  `note` varchar(255) DEFAULT NULL,
  `semester_at` varchar(255) DEFAULT NULL,
  `coding_target_type` enum('CODING_MAJOR','EXEMPT','NON_MAJOR') NOT NULL,
  `dept_group` enum('ACADEMIC_DIVISION_2','AI_CONVERGENCE_COLLEGE','ARTS_AND_PHYSICAL_EDUCATION_COLLEGE','BUSINESS_ADMINISTRATION_COLLEGE','BUSINESS_AND_ECONOMICS_COLLEGE','DAEYANG_HUMANITY_COLLEGE','ELECTRONICS_AND_INFORMATION_ENGINEERING_COLLEGE','ENGINEERING_COLLEGE','HOSPITALITY_AND_TOURISM_COLLEGE','INTERDISCIPLINARY_CONVERGENCE_MAJOR','LAW','LIBERAL_ARTS_COLLEGE','LIFE_SCIENCES_COLLEGE','NATURAL_SCIENCES_COLLEGE','SEJONG_INTERNATIONAL_COLLEGE','SOCIAL_SCIENCES_COLLEGE','SOFTWARE_CONVERGENCE_COLLEGE') NOT NULL,
  `english_target_type` enum('ENGLISH_MAJOR','EXEMPT','NON_MAJOR') NOT NULL,
  `updated_at` datetime(6) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
CREATE TABLE `id_generator` (
  `gen_name` varchar(255) NOT NULL,
  `gen_val` bigint DEFAULT NULL,
  PRIMARY KEY (`gen_name`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

INSERT INTO `id_generator` (`gen_name`, `gen_val`) VALUES ('schedule', 0);
CREATE TABLE `notices` (
  `is_deleted` bit(1) NOT NULL,
  `created_at` datetime(6) DEFAULT NULL,
  `deleted_at` datetime(6) DEFAULT NULL,
  `id` bigint NOT NULL AUTO_INCREMENT,
  `updated_at` datetime(6) DEFAULT NULL,
  `title` varchar(250) NOT NULL,
  `content` varchar(1000) NOT NULL,
  `semester_at` varchar(255) DEFAULT NULL,
  `operation_type` enum('ALL','BASKETS','GRADUATION','LIVE','PRESEAT','REVIEW','SIMULATION','TIMETABLE') NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
CREATE TABLE `official_schedule` (
  `id` bigint NOT NULL,
  `timetable_id` bigint DEFAULT NULL,
  `subject_id` bigint NOT NULL,
  `semester_at` varchar(255) DEFAULT NULL,
  `created_at` datetime(6) DEFAULT NULL,
  `deleted_at` datetime(6) DEFAULT NULL,
  `is_deleted` tinyint(1) DEFAULT NULL,
  `updated_at` datetime(6) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `fk_official_schedule_timetable` (`timetable_id`),
  KEY `fk_official_schedule_subject` (`subject_id`),
  CONSTRAINT `fk_official_schedule_subject` FOREIGN KEY (`subject_id`) REFERENCES `subjects` (`id`),
  CONSTRAINT `fk_official_schedule_timetable` FOREIGN KEY (`timetable_id`) REFERENCES `time_table` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
CREATE TABLE `periods` (
  `created_at` datetime(6) DEFAULT NULL,
  `is_deleted` bit(1) NOT NULL,
  `deleted_at` datetime(6) DEFAULT NULL,
  `end_date` datetime(6) DEFAULT NULL,
  `id` bigint NOT NULL AUTO_INCREMENT,
  `start_date` datetime(6) DEFAULT NULL,
  `message` varchar(255) DEFAULT NULL,
  `semester_at` varchar(255) DEFAULT NULL,
  `operation_type` enum('BASKETS','LIVE','PRESEAT','SIMULATION','TIMETABLE') DEFAULT NULL,
  `semester` enum('FALL_25','SPRING_25','SPRING_26','SUMMER_25','WINTER_25') DEFAULT NULL,
  `updated_at` datetime(6) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
CREATE TABLE `pins` (
  `created_at` timestamp(6) NOT NULL,
  `id` bigint NOT NULL AUTO_INCREMENT,
  `subject_id` bigint NOT NULL,
  `token` varchar(255) DEFAULT NULL,
  `is_deleted` tinyint(1) NOT NULL DEFAULT '0',
  `deleted_at` timestamp NULL DEFAULT NULL,
  `semester_at` varchar(255) DEFAULT '2025/1학기',
  `updated_at` datetime(6) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `FK_pins_subject` (`subject_id`),
  CONSTRAINT `FK_pins_subject` FOREIGN KEY (`subject_id`) REFERENCES `subjects` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
CREATE TABLE `required_courses` (
  `admission_year` int NOT NULL,
  `admission_year_short` int NOT NULL,
  `is_deleted` bit(1) NOT NULL,
  `required` bit(1) NOT NULL,
  `created_at` datetime(6) DEFAULT NULL,
  `deleted_at` datetime(6) DEFAULT NULL,
  `id` bigint NOT NULL AUTO_INCREMENT,
  `alt_group` varchar(255) DEFAULT NULL,
  `curi_nm` varchar(255) NOT NULL,
  `curi_no` varchar(255) NOT NULL,
  `dept_cd` varchar(255) NOT NULL,
  `dept_nm` varchar(255) NOT NULL,
  `note` varchar(255) DEFAULT NULL,
  `semester_at` varchar(255) DEFAULT NULL,
  `category_type` enum('ACADEMIC_BASIC','BALANCE_REQUIRED','COMMON_REQUIRED','GENERAL_ELECTIVE','MAJOR_BASIC','MAJOR_ELECTIVE','MAJOR_REQUIRED','TOTAL_COMPLETION') NOT NULL,
  `updated_at` datetime(6) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
CREATE TABLE `seats` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `subject_id` bigint DEFAULT NULL,
  `class_code` varchar(255) DEFAULT NULL,
  `curi_no` varchar(255) DEFAULT NULL,
  `dept_cd` varchar(255) DEFAULT NULL,
  `orgn_clsf_cd` varchar(255) DEFAULT NULL,
  `smt_cd` varchar(255) DEFAULT NULL,
  `student_div` varchar(255) DEFAULT NULL,
  `student_div_nm` varchar(255) DEFAULT NULL,
  `year` varchar(255) DEFAULT NULL,
  `out_limit_rcnt` int DEFAULT NULL,
  `out_limit_rcnt1` int DEFAULT NULL,
  `out_limit_rcnt2` int DEFAULT NULL,
  `out_limit_rcnt3` int DEFAULT NULL,
  `out_limit_rcnt4` int DEFAULT NULL,
  `remain_other_rcnt` int DEFAULT NULL,
  `remain_out_rcnt` int DEFAULT NULL,
  `remain_tot_rcnt` int DEFAULT NULL,
  `tot_limit_rcnt` int DEFAULT NULL,
  `tot_limit_rcnt1` int DEFAULT NULL,
  `tot_limit_rcnt2` int DEFAULT NULL,
  `tot_limit_rcnt3` int DEFAULT NULL,
  `tot_limit_rcnt4` int DEFAULT NULL,
  `tot_out_rcnt` int DEFAULT NULL,
  `tot_rcnt` int DEFAULT NULL,
  `created_date` date NOT NULL DEFAULT (curdate()),
  `is_deleted` tinyint(1) NOT NULL DEFAULT '0',
  `deleted_at` timestamp NULL DEFAULT NULL,
  `semester_at` varchar(255) DEFAULT '2025/1학기',
  `created_at` timestamp(6) NULL DEFAULT NULL,
  `updated_at` datetime(6) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `FK_seats_subject` (`subject_id`),
  CONSTRAINT `FK_seats_subject` FOREIGN KEY (`subject_id`) REFERENCES `subjects` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
CREATE TABLE `subjects` (
  `created_at` timestamp(6) NULL DEFAULT NULL,
  `id` bigint NOT NULL AUTO_INCREMENT,
  `cdt` varchar(255) DEFAULT NULL,
  `class` varchar(255) DEFAULT NULL,
  `cors_unit_grp_cd` varchar(255) DEFAULT NULL,
  `cors_unit_grp_cd_nm` varchar(255) DEFAULT NULL,
  `curi_lang_cd` varchar(255) DEFAULT NULL,
  `curi_lang_nm` varchar(255) DEFAULT NULL,
  `curi_nm` varchar(255) DEFAULT NULL,
  `curi_no` varchar(255) DEFAULT NULL,
  `curi_type_cd` varchar(255) DEFAULT NULL,
  `curi_type_cd_nm` varchar(255) DEFAULT NULL,
  `cyber_type_cd_nm` varchar(255) DEFAULT NULL,
  `dept_cd` varchar(255) DEFAULT NULL,
  `inout_sub_cdt_exchange_yn` varchar(255) DEFAULT NULL,
  `internship_type_cd_nm` varchar(255) DEFAULT NULL,
  `lesn_emp` varchar(255) DEFAULT NULL,
  `lesn_room` varchar(255) DEFAULT NULL,
  `lesn_time` varchar(255) DEFAULT NULL,
  `manage_dept_nm` varchar(255) DEFAULT NULL,
  `orgn_clsf_cd` varchar(255) DEFAULT NULL,
  `orgn_clsf_cd_nm` varchar(255) DEFAULT NULL,
  `plan_reg_yn` varchar(255) DEFAULT NULL,
  `prt_ord` varchar(255) DEFAULT NULL,
  `remark` varchar(255) DEFAULT NULL,
  `sch_dept_alias` varchar(255) DEFAULT NULL,
  `semester_at` varchar(255) DEFAULT NULL,
  `slt_domain_cd` varchar(255) DEFAULT NULL,
  `slt_domain_cd_nm` varchar(255) DEFAULT NULL,
  `smt_cd` varchar(255) DEFAULT NULL,
  `smt_cd_nm` varchar(255) DEFAULT NULL,
  `student_year` varchar(255) DEFAULT NULL,
  `tm_num` varchar(255) DEFAULT NULL,
  `tot_tm_num` varchar(255) DEFAULT NULL,
  `year` varchar(255) DEFAULT NULL,
  `year_smt_nm` varchar(255) DEFAULT NULL,
  `everytime_lecture_id` bigint DEFAULT NULL,
  `is_deleted` tinyint(1) NOT NULL DEFAULT '0',
  `deleted_at` timestamp NULL DEFAULT NULL,
  `updated_at` datetime(6) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
CREATE TABLE `time_table` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `token` varchar(255) DEFAULT NULL,
  `time_table_name` varchar(255) DEFAULT NULL,
  `semester` varchar(255) DEFAULT NULL,
  `semester_at` varchar(255) DEFAULT NULL,
  `created_at` datetime(6) DEFAULT NULL,
  `deleted_at` datetime(6) DEFAULT NULL,
  `is_deleted` tinyint(1) DEFAULT NULL,
  `updated_at` datetime(6) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
CREATE TABLE `user_review` (
  `rate` smallint DEFAULT NULL,
  `id` bigint NOT NULL AUTO_INCREMENT,
  `detail` varchar(255) DEFAULT NULL,
  `student_id` varchar(255) DEFAULT NULL,
  `operation_type` enum('BASKETS','GRADUATION','LIVE','PRESEAT','SIMULATION','TIMETABLE') DEFAULT NULL,
  `updated_at` datetime(6) DEFAULT NULL,
  `semester_at` varchar(255) DEFAULT NULL,
  `created_at` datetime(6) DEFAULT NULL,
  `deleted_at` datetime(6) DEFAULT NULL,
  `is_deleted` tinyint(1) NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
CREATE TABLE `users` (
  `admission_year` int NOT NULL,
  `is_deleted` bit(1) NOT NULL,
  `created_at` datetime(6) DEFAULT NULL,
  `deleted_at` datetime(6) DEFAULT NULL,
  `id` bigint NOT NULL AUTO_INCREMENT,
  `college_nm` varchar(255) DEFAULT NULL,
  `dept_cd` varchar(255) DEFAULT NULL,
  `dept_nm` varchar(255) DEFAULT NULL,
  `double_college_nm` varchar(255) DEFAULT NULL,
  `double_dept_cd` varchar(255) DEFAULT NULL,
  `double_dept_nm` varchar(255) DEFAULT NULL,
  `name` varchar(255) DEFAULT NULL,
  `semester_at` varchar(255) DEFAULT NULL,
  `student_id` varchar(255) DEFAULT NULL,
  `major_type` enum('ALL','DOUBLE','SINGLE') DEFAULT NULL,
  `updated_at` datetime(6) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

SET FOREIGN_KEY_CHECKS = 1;
