ALTER TABLE `completed_courses` MODIFY COLUMN `category_type`
    enum('COMMON_REQUIRED','BALANCE_REQUIRED','ACADEMIC_BASIC','GENERAL_ELECTIVE','GENERAL','MAJOR_REQUIRED','MAJOR_ELECTIVE','MAJOR_BASIC','ROTC','ETC','TOTAL_COMPLETION') DEFAULT NULL;
